version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'device-mcs-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      user_device_network:
  spring-demo-device:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_DBNAME=device-mcs-db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      user_device_network:
        ipv4_address: 172.30.1.3

volumes:
  my-db:

networks:
  user_device_network:
    external: true
